name: rental
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  khalti_flutter: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0
  intl: ^0.18.1
  month_year_picker: ^0.3.0+1
  flutter_map: ^6.1.0
  latlng: ^2.0.7
  path_provider: ^2.1.3
  pdf: ^3.10.8
  open_file: ^3.3.2
  fl_chart: ^0.67.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true 


  assets:     
         - assets/images/
